<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddtocartLoc</name>
   <tag></tag>
   <elementGuidId>63cd5b9d-d7a9-4b45-bdee-291a65fef15c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[data-hook='add-to-cart']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
