<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frameLoc</name>
   <tag></tag>
   <elementGuidId>e63bb838-5bfe-4df8-955d-c6de523674c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[class='_2QAyo']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
