<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frameCloseBtnLoc</name>
   <tag></tag>
   <elementGuidId>eeba00f0-1040-4a1a-9113-c7ba7974e977</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[id='cart-widget-close']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
