<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ProductPriceLoc</name>
   <tag></tag>
   <elementGuidId>de899c85-5c21-443e-841e-0862f4010832</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[class='item-name']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
