<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>emailtextfieldLoc</name>
   <tag></tag>
   <elementGuidId>37f38941-f73f-4ec9-b31a-9061a92f8e34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name='email-address']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
