<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>submitBtnLoc</name>
   <tag></tag>
   <elementGuidId>dbf34db0-67ac-4b25-8d32-35a170d10633</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[id='comp-kiaj7o6t']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
