<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>subscribeTextloc</name>
   <tag></tag>
   <elementGuidId>e04c0169-7a23-456b-9b5e-4a36e42120df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[id='comp-kiaj7o73']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
