<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>subscribeformtext</name>
   <tag></tag>
   <elementGuidId>6a1194aa-dc78-49bc-ad8f-152389b2b110</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[id='comp-kiaj7o5a']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
