<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addressLoc</name>
   <tag></tag>
   <elementGuidId>0c6b6cf9-edf3-41e5-b0b4-9892d931954a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[id='input_comp-kia8grv2']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
