<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>confirmationtextloc</name>
   <tag></tag>
   <elementGuidId>eb0badd7-1689-41a0-ae71-4bc0bfd9193e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[id='comp-kia8grvx']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
