<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>emailLoc</name>
   <tag></tag>
   <elementGuidId>5200d013-ee0b-479e-a8c7-194fa5b965f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[id='input_comp-kia8grv62']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
