<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>messageboxloc</name>
   <tag></tag>
   <elementGuidId>e38e849f-df72-4f4c-8ad9-501f6a054908</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea[id='textarea_comp-kia8grvl1']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
