<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nameLoc</name>
   <tag></tag>
   <elementGuidId>a67f2a82-80e4-4506-98a5-07bfdd8f43d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[id='input_comp-kia8grux']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
