<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>phoneloc</name>
   <tag></tag>
   <elementGuidId>53281751-f1fd-4469-ae45-23a91f72ec61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[id='input_comp-kia8grva']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
