<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>subjectLoc</name>
   <tag></tag>
   <elementGuidId>feed105a-cecd-4a4d-a176-d11eab346ab2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[id='input_comp-kia8grve']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
