<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>submibtnLoc</name>
   <tag></tag>
   <elementGuidId>93e3dd8f-0a8c-41d4-8782-252e0dbf942d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[id='comp-kia8grw11']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
